services:
  - type: web
    name: finance-tracker-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString